"""Cambiar fecha a DateTime en Venta

Revision ID: 349814153e67
Revises: 
Create Date: 2025-04-09 12:59:06.720215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '349814153e67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_ventas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detalle_ventas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('venta_id', sa.INTEGER(), nullable=False),
    sa.Column('producto_id', sa.INTEGER(), nullable=False),
    sa.Column('cantidad', sa.INTEGER(), nullable=True),
    sa.Column('precio_unitario', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
